### ISSUE TITLE
Saving stream times out

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-api#2]
/stream/xxxxxx/edit
(change title …)
Click "save stream"
… says "saving", but never finishes

**Comment by fjenett** [comment]
… or is this a frontend issue?

**Comment by fjenett** [comment]
Sorry … seems to be frontend. I'll repost there.

**Comment by dasantonym** [comment]
if it doesn't throw api errors in the console or loads non 200 http code responses it is most likely frontend.
