### ISSUE TITLE
delivers Date objects as string but not quoted

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-api#3]
```
{ created: Thu Apr 09 2015 03:57:21 GMT+0200 (CEST),  description: '...',  namespace: '40266e5d-efef-4150-844a-0aa696eabb89',  title: 'Deborah Hay (Test) / No Time To Fly',  updated: Thu Apr 09 2015 03:57:21 GMT+0200 (CEST),  user_uuid: '619602d0-f912-56ac-b494-3a3b4d1c74a3',  uuid: 'eb471dcb-af2f-45a9-870c-909e069bccbf' }
```

… hence parsing as JSON fails for me

**Comment by fjenett** [comment]
That is for: http://192.168.56.101/packages/eb471dcb-af2f-45a9-870c-909e069bccbf

**Comment by fjenett** [comment]
Got it … need to explicitly set "Content-Type":"application/json". But still the response given without explicitly stating this looks like json and if it is should be valid, no?

**Comment by dasantonym** [comment]
hm, this is interesting. actually you either supply a content type or a file extension to get the right format. however, when neither is given it assumes json.

so you say when you don't specify a content type you get another date format than with a content type? what about adding a .json extension. side note: doesn't happen on my machine. might be some problem with this specific installation.

i'll check with my copy of the vm!

**Comment by denjello** [comment]
Not sure if this will help or even solves the problem, but this approach will probably speed up the DB on deserialization.

From the [mongodb api resource page](http://api.mongodb.org/perl/current/MongoDB/DataTypes.html#Dates):

```
Warning: creating DateTime objects is extremely slow. 
Consider saving dates as numbers and converting the 
numbers to DateTimes when needed. A single DateTime 
field can make deserialization up to 10 times slower.

For example, you could use the time function to store seconds 
since the epoch:

    $collection->update($criteria, {'$set' => {"last modified" => time()}})

This will be faster to deserialize. 
```

**Comment by dasantonym** [comment]
if the date format turns out to be different depending on the runtime environment this might help in making the date one fixed format and not leaving it to whatever is messing it up (my guess: mongoose)

sounds like a good idea to me!

**Comment by denjello** [comment]
of course that is from the perldocs, but maybe a method to fix this quick.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getUTCMilliseconds

`dateObj.getUTCMilliseconds()`

**Comment by fjenett** [comment]
+1 … PM2 has utc millis as well for that reason.

**Comment by denjello** [comment]
Wasn't there at some point a problem keeping time / frame dropping? I bet with mtime you've got one less problem (or at least a simpler problem) for the javascript VM to solve...

**Comment by dasantonym** [comment]
that's another can of worms, but not an immediate issue right now. i'll go with the millis for the date objects and set up a migration.

**Comment by dasantonym** [comment]
pinning the mongoose version fixed this in terms of the invalid json. still needs to be adresses though... https://github.com/PieceMeta/piecemeta-api/issues/4
